// Array de Productos
export const productos = [
    {
        idProducto: 11,
        nombre: 'Caño de Cobre',
        tipo: '1/4"',
        precio: 4.49,
        unidad: 'mt',
        cantidad: 1,
        imagen: './assets/productos/01-cobre.jpg',
    },
    {
        idProducto: 12,
        nombre: 'Caño de Cobre',
        tipo: '5/16"',
        precio: 5.67,
        unidad: 'mt',
        cantidad: 1,
        imagen: './assets/productos/01-cobre.jpg',
    },
    {
        idProducto: 13,
        nombre: 'Caño de Cobre',
        tipo: '3/8"',
        precio: 7.15,
        unidad: 'mt',
        cantidad: 1,
        imagen: './assets/productos/01-cobre.jpg',
    },
    {
        idProducto: 14,
        nombre: 'Caño de Cobre',
        tipo: '1/2"',
        precio: 9.67,
        unidad: 'mt',
        cantidad: 1,
        imagen: './assets/productos/01-cobre.jpg',
    },
    {
        idProducto: 15,
        nombre: 'Caño de Cobre',
        tipo: '5/8"',
        precio: 12.46,
        unidad: 'mt',
        cantidad: 1,
        imagen: './assets/productos/01-cobre.jpg',
    },
    {
        idProducto: 16,
        nombre: 'Caño de Cobre',
        tipo: '3/4"',
        precio: 14.30,
        unidad: 'mt',
        cantidad: 1,
        imagen: './assets/productos/01-cobre.jpg',
    },
    {
        idProducto: 21,
        nombre: 'Aislación Elastomérica 9mm',
        tipo: '1/4"',
        precio: 2.07,
        unidad: 'tira 2mt',
        cantidad: 1,
        imagen: './assets/productos/02-aislacion.jpg',
    },
    {
        idProducto: 22,
        nombre: 'Aislación Elastomérica 9mm',
        tipo: '5/16"',
        precio: 2.14,
        unidad: 'tira 2mt',
        cantidad: 1,
        imagen: './assets/productos/02-aislacion.jpg',
    },
    {
        idProducto: 23,
        nombre: 'Aislación Elastomérica 9mm',
        tipo: '3/8"',
        precio: 2.21,
        unidad: 'tira 2mt',
        cantidad: 1,
        imagen: './assets/productos/02-aislacion.jpg',
    },
    {
        idProducto: 24,
        nombre: 'Aislación Elastomérica 9mm',
        tipo: '1/2"',
        precio: 2.51,
        unidad: 'tira 2mt',
        cantidad: 1,
        imagen: './assets/productos/02-aislacion.jpg',
    },
    {
        idProducto: 25,
        nombre: 'Aislación Elastomérica 9mm',
        tipo: '5/8"',
        precio: 2.80,
        unidad: 'tira 2mt',
        cantidad: 1,
        imagen: './assets/productos/02-aislacion.jpg',
    },
    {
        idProducto: 26,
        nombre: 'Aislación Elastomérica 9mm',
        tipo: '3/4"',
        precio: 3.10,
        unidad: 'tira 2mt',
        cantidad: 1,
        imagen: './assets/productos/02-aislacion.jpg',
    },
    {
        idProducto: 31,
        nombre: 'Gases Refrigerantes',
        tipo: 'R22',
        precio: 30.28,
        unidad: 'cápsula',
        cantidad: 1,
        imagen: './assets/productos/03-gases.jpg',
    },
    {
        idProducto: 32,
        nombre: 'Gases Refrigerantes',
        tipo: 'R410',
        precio: 14.57,
        unidad: 'cápsula',
        cantidad: 1,
        imagen: './assets/productos/03-gases.jpg',
    },
    {
        idProducto: 33,
        nombre: 'Gases Refrigerantes',
        tipo: 'R134',
        precio: 12.33,
        unidad: 'cápsula',
        cantidad: 1,
        imagen: './assets/productos/03-gases.jpg',
    },
    {
        idProducto: 34,
        nombre: 'Gases Refrigerantes',
        tipo: 'R404',
        precio: 15.83,
        unidad: 'cápsula',
        cantidad: 1,
        imagen: './assets/productos/03-gases.jpg',
    },
    {
        idProducto: 35,
        nombre: 'Gases Refrigerantes',
        tipo: 'MO49',
        precio: 17.57,
        unidad: 'cápsula',
        cantidad: 1,
        imagen: './assets/productos/03-gases.jpg',
    },
    {
        idProducto: 36,
        nombre: 'Gases Refrigerantes',
        tipo: '141b',
        precio: 25.84,
        unidad: 'cápsula',
        cantidad: 1,
        imagen: './assets/productos/03-gases.jpg',
    },
    {
        idProducto: 41,
        nombre: 'Cable Taller',
        tipo: '3x1.5mm"',
        precio: 1.13,
        unidad: 'mt',
        cantidad: 1,
        imagen: './assets/productos/04-cable.jpg',
    },
    {
        idProducto: 42,
        nombre: 'Cable Taller',
        tipo: '3x2.5mm',
        precio: 1.60,
        unidad: 'mt',
        cantidad: 1,
        imagen: './assets/productos/04-cable.jpg',
    },
    {
        idProducto: 43,
        nombre: 'Cable Taller',
        tipo: '4x1.5mm',
        precio: 1.24,
        unidad: 'mt',
        cantidad: 1,
        imagen: './assets/productos/04-cable.jpg',
    },
    {
        idProducto: 44,
        nombre: 'Cable Taller',
        tipo: '5x1.5mm',
        precio: 1.73,
        unidad: 'mt',
        cantidad: 1,
        imagen: './assets/productos/04-cable.jpg',
    },
    {
        idProducto: 45,
        nombre: 'Cable Taller',
        tipo: '5x2.5mm',
        precio: 2.53,
        unidad: 'mt',
        cantidad: 1,
        imagen: './assets/productos/04-cable.jpg',
    },
    {
        idProducto: 51,
        nombre: 'Manguera Cristal',
        tipo: '1/4"',
        precio: 0.22,
        unidad: 'mt',
        cantidad: 1,
        imagen: './assets/productos/05-manguera.jpg',
    },
    {
        idProducto: 52,
        nombre: 'Manguera Cristal',
        tipo: '1/2"',
        precio: 0.37,
        unidad: 'mt',
        cantidad: 1,
        imagen: './assets/productos/05-manguera.jpg',
    },
    {
        idProducto: 53,
        nombre: 'Manguera Cristal',
        tipo: '5/8"',
        precio: 0.52,
        unidad: 'mt',
        cantidad: 1,
        imagen: './assets/productos/05-manguera.jpg',
    },
    {
        idProducto: 61,
        nombre: 'Cinta de PVC',
        tipo: 'Tacsa Blanca S/adh',
        precio: 3.17,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/06-cinta.jpg',
    },
    {
        idProducto: 62,
        nombre: 'Cinta de PVC',
        tipo: 'Tacsa Blanca C/adh',
        precio: 5.12,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/06-cinta.jpg',
    },
    {
        idProducto: 63,
        nombre: 'Cinta de PVC',
        tipo: 'Económica Blanca S/adh',
        precio: 2.92,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/06-cinta.jpg',
    },
    {
        idProducto: 64,
        nombre: 'Cinta de PVC',
        tipo: 'Económica Blanca C/adh',
        precio: 3.65,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/06-cinta.jpg',
    },
    {
        idProducto: 71,
        nombre: 'Ménsulas Reforzadas',
        tipo: 'M42 Epoxi',
        precio: 14.01,
        unidad: 'juego',
        cantidad: 1,
        imagen: './assets/productos/07-mensulas.jpg',
    },
    {
        idProducto: 72,
        nombre: 'Ménsulas Reforzadas',
        tipo: 'M49 Epoxi',
        precio: 14.39,
        unidad: 'juego',
        cantidad: 1,
        imagen: './assets/productos/07-mensulas.jpg',
    },
    {
        idProducto: 73,
        nombre: 'Ménsulas Reforzadas',
        tipo: 'M62 Epoxi',
        precio: 18.90,
        unidad: 'juego',
        cantidad: 1,
        imagen: './assets/productos/07-mensulas.jpg',
    },
    {
        idProducto: 74,
        nombre: 'Ménsulas Reforzadas',
        tipo: 'Económica 40cm',
        precio: 8.83,
        unidad: 'juego',
        cantidad: 1,
        imagen: './assets/productos/07-mensulas.jpg',
    },
    {
        idProducto: 75,
        nombre: 'Ménsulas Reforzadas',
        tipo: 'Económica 50cm',
        precio: 10.81,
        unidad: 'juego',
        cantidad: 1,
        imagen: './assets/productos/07-mensulas.jpg',
    },
    {
        idProducto: 76,
        nombre: 'Ménsulas Reforzadas',
        tipo: 'Económica 60cm',
        precio: 17.86,
        unidad: 'juego',
        cantidad: 1,
        imagen: './assets/productos/07-mensulas.jpg',
    },
    {
        idProducto: 81,
        nombre: 'Motocompresores',
        tipo: '1/6HP',
        precio: 93.79,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/08-compresores.jpg',
    },
    {
        idProducto: 82,
        nombre: 'Motocompresores',
        tipo: '1/5HP',
        precio: 97.33,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/08-compresores.jpg',
    },
    {
        idProducto: 83,
        nombre: 'Motocompresores',
        tipo: '1/4HP',
        precio: 116.43,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/08-compresores.jpg',
    },
    {
        idProducto: 84,
        nombre: 'Motocompresores',
        tipo: '1/4+HP',
        precio: 118.52,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/08-compresores.jpg',
    },
    {
        idProducto: 85,
        nombre: 'Motocompresores',
        tipo: '1/3HP',
        precio: 135.20,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/08-compresores.jpg',
    },
    {
        idProducto: 86,
        nombre: 'Motocompresores',
        tipo: '1/3+HP',
        precio: 139.39,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/08-compresores.jpg',
    },
    {
        idProducto: 91,
        nombre: 'Herramientas',
        tipo: 'Manifold VALUE R22',
        precio: 105.84,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/09-herramientas.jpg',
    },
    {
        idProducto: 92,
        nombre: 'Herramientas',
        tipo: 'Manifold VALUE R410',
        precio: 119.91,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/09-herramientas.jpg',
    },
    {
        idProducto: 93,
        nombre: 'Herramientas',
        tipo: 'Bomba de Vacio i240 VALUE',
        precio: 344.78,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/09-herramientas.jpg',
    },
    {
        idProducto: 94,
        nombre: 'Herramientas',
        tipo: 'Llave crique VALUE',
        precio: 8.40,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/09-herramientas.jpg',
    },
    {
        idProducto: 95,
        nombre: 'Herramientas',
        tipo: 'Pinza selladora VALUE',
        precio: 11.19,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/09-herramientas.jpg',
    },
    {
        idProducto: 96,
        nombre: 'Herramientas',
        tipo:  'Pinza cortacapilar VALUE',
        precio: 12.70,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/09-herramientas.jpg',
    },
    {
        idProducto: 101,
        nombre: 'Accesorios',
        tipo: 'Caja Preinstalación SARSA',
        precio: 4.73,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/10-accesorios.jpg',
    },
    {
        idProducto: 102,
        nombre: 'Accesorios',
        tipo: 'Tirafondo+Tarugo N°10',
        precio: 0.24,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/10-accesorios.jpg',
    },
    {
        idProducto: 103,
        nombre: 'Accesorios',
        tipo: 'Tornillo+Tarugo N°6',
        precio: 0.07,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/10-accesorios.jpg',
    },
    {
        idProducto: 104,
        nombre: 'Accesorios',
        tipo: 'Patas de Goma p/piso',
        precio: 2.04,
        unidad: 'juego',
        cantidad: 1,
        imagen: './assets/productos/10-accesorios.jpg',
    },
    {
        idProducto: 105,
        nombre: 'Accesorios',
        tipo: 'Patas de Goma p/ménsula',
        precio: 1.72,
        unidad: 'juego',
        cantidad: 1,
        imagen: './assets/productos/10-accesorios.jpg',
    },
    {
        idProducto: 106,
        nombre: 'Accesorios',
        tipo: 'Pico Drenaje AA SARSA',
        precio: 0.83,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/10-accesorios.jpg',
    },
    {
        idProducto: 111,
        nombre: 'Varios',
        tipo: 'Control Remoto Universal',
        precio: 5.37,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/11-varios.jpg',
    },
    {
        idProducto: 112,
        nombre: 'Varios',
        tipo: 'Pila AAA',
        precio: 0.58,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/11-varios.jpg',
    },
    {
        idProducto: 113,
        nombre: 'Varios',
        tipo: 'Pila AA',
        precio: 0.51,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/11-varios.jpg',
    },
    {
        idProducto: 114,
        nombre: 'Varios',
        tipo: 'Bomba Drenaje Flowita 10l/h',
        precio: 78.21,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/11-varios.jpg',
    },
    {
        idProducto: 121,
        nombre: 'Aire Acondicionado',
        tipo: 'TRANE 2250fr ON-OFF',
        precio: 444,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/12-aireacondicionado.jpg',
    },
    {
        idProducto: 122,
        nombre: 'Aire Acondicionado',
        tipo: 'TRANE 3000fr ON-OFF',
        precio: 489,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/12-aireacondicionado.jpg',
    },
    {
        idProducto: 123,
        nombre: 'Aire Acondicionado',
        tipo: 'TRANE 4500fr ON-OFF',
        precio: 728,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/12-aireacondicionado.jpg',
    },
    {
        idProducto: 124,
        nombre: 'Aire Acondicionado',
        tipo: 'TRANE 6000fr ON-OFF',
        precio: 871,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/12-aireacondicionado.jpg',
    },
    {
        idProducto: 125,
        nombre: 'Aire Acondicionado',
        tipo: 'TRANE 2250fr INVERTER',
        precio: 595,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/12-aireacondicionado.jpg',
    },
    {
        idProducto: 126,
        nombre: 'Aire Acondicionado',
        tipo: 'TRANE 3000fr INVERTER',
        precio: 619,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/12-aireacondicionado.jpg',
    },
    {
        idProducto: 127,
        nombre: 'Aire Acondicionado',
        tipo: 'TRANE 4500fr INVERTER',
        precio: 892,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/12-aireacondicionado.jpg',
    },
    {
        idProducto: 128,
        nombre: 'Aire Acondicionado',
        tipo:  'TRANE 6000fr INVERTER',
        precio: 1105,
        unidad: 'unidad',
        cantidad: 1,
        imagen: './assets/productos/12-aireacondicionado.jpg',
    },
]

class Producto {
    constructor(idProducto, nombre, tipo, precio, unidad, cantidad, imagen) {
        this.idProducto = idProducto;
        this.nombre = nombre;
        this.tipo = tipo;
        this.precio = precio;
        this.unidad = unidad;
        this.cantidad = cantidad;
        this.imagen = imagen;
    }
}